/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    // Overridden (not extended) so stray defaults can't leak into the system.
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    spacing: {
      0: "var(--space-0)",
      1: "var(--space-1)",
      2: "var(--space-2)",
      3: "var(--space-3)",
      4: "var(--space-4)",
      5: "var(--space-5)",
      6: "var(--space-6)",
      8: "var(--space-8)",
      10: "var(--space-10)",
      12: "var(--space-12)",
      16: "var(--space-16)",
      20: "var(--space-20)",
      24: "var(--space-24)",
      32: "var(--space-32)",
      40: "var(--space-40)",
      px: "1px",
      // semantic aliases
      "inline-tight": "var(--space-inline-tight)",
      inline: "var(--space-inline)",
      "stack-tight": "var(--space-stack-tight)",
      stack: "var(--space-stack)",
      "stack-loose": "var(--space-stack-loose)",
      section: "var(--space-section)",
      "section-lg": "var(--space-section-lg)",
      gutter: "var(--space-gutter)",
      "gutter-lg": "var(--space-gutter-lg)",
    },
    fontWeight: {
      normal: "var(--font-weight-regular)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
    },
    extend: {
      colors: {
        // Layer 0. Exposed for rare cases only — prefer the semantic names
        // below, which are what product theming actually swaps.
        brandscale: {
          100: "rgb(var(--brand-100) / <alpha-value>)",
          300: "rgb(var(--brand-300) / <alpha-value>)",
          400: "rgb(var(--brand-400) / <alpha-value>)",
          600: "rgb(var(--brand-600) / <alpha-value>)",
          700: "rgb(var(--brand-700) / <alpha-value>)",
        },
        bg: {
          canvas: "rgb(var(--color-bg-canvas) / <alpha-value>)",
          surface: "rgb(var(--color-bg-surface) / <alpha-value>)",
          "surface-raised": "rgb(var(--color-bg-surface-raised) / <alpha-value>)",
        },
        border: {
          DEFAULT: "rgb(var(--color-border-default) / <alpha-value>)",
          strong: "rgb(var(--color-border-strong) / <alpha-value>)",
          // Boundaries that identify a control. Clears 3:1 — use this on
          // inputs and selects, not the decorative seam above.
          control: "rgb(var(--color-border-control) / <alpha-value>)",
        },
        text: {
          primary: "rgb(var(--color-text-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-text-secondary) / <alpha-value>)",
          muted: "rgb(var(--color-text-muted) / <alpha-value>)",
        },
        brand: {
          primary: "rgb(var(--color-brand-primary) / <alpha-value>)",
          "primary-hover": "rgb(var(--color-brand-primary-hover) / <alpha-value>)",
          subtle: "rgb(var(--color-brand-subtle) / <alpha-value>)",
        },
        accent: {
          highlight: "rgb(var(--color-accent-highlight) / <alpha-value>)",
          "highlight-bg": "rgb(var(--color-accent-highlight-bg) / <alpha-value>)",
          "highlight-text": "rgb(var(--color-accent-highlight-text) / <alpha-value>)",
        },
        // Charts. Series cap at 5 — see design-tokens.html for why.
        chart: {
          1: "rgb(var(--chart-series-1) / <alpha-value>)",
          2: "rgb(var(--chart-series-2) / <alpha-value>)",
          3: "rgb(var(--chart-series-3) / <alpha-value>)",
          4: "rgb(var(--chart-series-4) / <alpha-value>)",
          5: "rgb(var(--chart-series-5) / <alpha-value>)",
          grid: "rgb(var(--chart-grid) / <alpha-value>)",
          axis: "rgb(var(--chart-axis) / <alpha-value>)",
          label: "rgb(var(--chart-label) / <alpha-value>)",
          baseline: "rgb(var(--chart-baseline) / <alpha-value>)",
        },
        seq: {
          0: "rgb(var(--chart-seq-0) / <alpha-value>)",
          1: "rgb(var(--chart-seq-1) / <alpha-value>)",
          2: "rgb(var(--chart-seq-2) / <alpha-value>)",
          3: "rgb(var(--chart-seq-3) / <alpha-value>)",
          4: "rgb(var(--chart-seq-4) / <alpha-value>)",
          5: "rgb(var(--chart-seq-5) / <alpha-value>)",
        },
        div: {
          neg3: "rgb(var(--chart-div-neg3) / <alpha-value>)",
          neg2: "rgb(var(--chart-div-neg2) / <alpha-value>)",
          neg1: "rgb(var(--chart-div-neg1) / <alpha-value>)",
          mid: "rgb(var(--chart-div-mid) / <alpha-value>)",
          pos1: "rgb(var(--chart-div-pos1) / <alpha-value>)",
          pos2: "rgb(var(--chart-div-pos2) / <alpha-value>)",
          pos3: "rgb(var(--chart-div-pos3) / <alpha-value>)",
        },
        status: {
          success: "rgb(var(--color-status-success) / <alpha-value>)",
          "success-bg": "rgb(var(--color-status-success-bg) / <alpha-value>)",
          "success-text": "rgb(var(--color-status-success-text) / <alpha-value>)",
          danger: "rgb(var(--color-status-danger) / <alpha-value>)",
          "danger-bg": "rgb(var(--color-status-danger-bg) / <alpha-value>)",
          "danger-text": "rgb(var(--color-status-danger-text) / <alpha-value>)",
          warning: "rgb(var(--color-status-warning) / <alpha-value>)",
          "warning-bg": "rgb(var(--color-status-warning-bg) / <alpha-value>)",
          "warning-text": "rgb(var(--color-status-warning-text) / <alpha-value>)",
          info: "rgb(var(--color-status-info) / <alpha-value>)",
          "info-bg": "rgb(var(--color-status-info-bg) / <alpha-value>)",
          "info-text": "rgb(var(--color-status-info-text) / <alpha-value>)",
        },
      },
      fontFamily: {
        display: "var(--font-display)",
        sans: "var(--font-body)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        "3xs": ["var(--text-3xs)", { lineHeight: "var(--leading-snug)" }],
        "2xs": ["var(--text-2xs)", { lineHeight: "var(--leading-snug)" }],
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-snug)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-normal)" }],
        base: ["var(--text-base)", { lineHeight: "var(--leading-normal)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-normal)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-display)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--leading-display)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--leading-display)" }],
        "4xl": ["var(--text-4xl)", { lineHeight: "var(--leading-display)" }],
        "5xl": ["var(--text-5xl)", { lineHeight: "var(--leading-tight)" }],
        "6xl": ["var(--text-6xl)", { lineHeight: "var(--leading-tight)" }],
      },
      lineHeight: {
        none: "var(--leading-none)",
        tight: "var(--leading-tight)",
        display: "var(--leading-display)",
        snug: "var(--leading-snug)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
      },
      letterSpacing: {
        display: "var(--tracking-display)",
        heading: "var(--tracking-heading)",
        normal: "var(--tracking-normal)",
        label: "var(--tracking-label)",
      },
      maxWidth: {
        prose: "var(--container-prose)",
        content: "var(--container-content)",
        wide: "var(--container-wide)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      borderWidth: {
        hairline: "var(--border-hairline)",
        thin: "var(--border-thin)",
        thick: "var(--border-thick)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
        "state-focus": "var(--state-focus-ring)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        base: "var(--duration-base)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        entrance: "var(--ease-entrance)",
        exit: "var(--ease-exit)",
      },
      zIndex: {
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        toast: "var(--z-toast)",
      },
      height: {
        "control-sm": "var(--control-height-sm)",
        "control-md": "var(--control-height-md)",
        "control-lg": "var(--control-height-lg)",
      },
      minHeight: {
        "control-sm": "var(--control-height-sm)",
        "control-md": "var(--control-height-md)",
        "control-lg": "var(--control-height-lg)",
      },
      backgroundColor: {
        "state-hover": "var(--state-hover-bg)",
        "state-press": "var(--state-press-bg)",
        "state-selected": "var(--state-selected-bg)",
        "state-skeleton": "var(--state-skeleton-bg)",
      },
      opacity: {
        disabled: "var(--opacity-disabled)",
        "state-disabled": "var(--state-disabled-opacity)",
        muted: "var(--opacity-muted)",
        overlay: "var(--opacity-overlay)",
      },
    },
  },
  plugins: [
    // Numeric utilities: `.tabular` for anything that updates in place.
    function ({ addUtilities }) {
      addUtilities({
        ".tabular": { fontVariantNumeric: "var(--numeric-tabular)" },
        ".proportional": { fontVariantNumeric: "var(--numeric-proportional)" },
      });
    },
  ],
};
